In [1]:
import numpy as np

def find_data_pv_function(data, pv_range):
    '''
    Find peaks and valleys of the data, excluding the first and last data points.

    Args:
        data: numpy.ndarray
            The input data array.
        pv_range: int
            The range within which peaks and valleys are detected.

    Returns:
        pv: numpy.ndarray
            An array of the same shape as `data`, where peaks are represented by 1,
            valleys are represented by -1, and other points are represented by 0.

    Raises:
        None
    '''
    pv = np.zeros_like(data)
    for col in range(0, data.shape[0]):
        print('+++++')
        print(col)
        print('+++++')
        for row in range(1, data.shape[1]-1):
            if row < pv_range:
                print('0', row+pv_range+1)
                print(data[col, row],  data[col, :row+pv_range+1])
                print(data[col, :row+pv_range+1].max())
                print('----')
                if data[col, row] == data[col, :row+pv_range+1].max():
                    pv[col, row] = 1 
                if data[col, row] == data[col, :row+pv_range+1].min():
                    pv[col, row] = -1
            else:
                print(row-pv_range, row+pv_range+1)
                print(data[col, row],  data[col, row-pv_range:row+pv_range+1])
                print(data[col, row-pv_range:row+pv_range+1].max())
                print('----')
                if data[col, row] == data[col, row-pv_range:row+pv_range+1].max():
                    pv[col, row] = 1
                if data[col, row] == data[col, row-pv_range:row+pv_range+1].min():
                    pv[col, row] = -1
    return pv


In [2]:
train_data = np.ndarray((2, 10))
train_data[0, :] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
train_data[1, :] = [0, -100, 2, 100, 4, 5, 6, 7, 8, 9]

In [3]:
pv_range = 2
train_data_pv = find_data_pv_function(train_data, pv_range)

+++++
0
+++++
0 4
1.0 [0. 1. 2. 3.]
3.0
----
0 5
2.0 [0. 1. 2. 3. 4.]
4.0
----
1 6
3.0 [1. 2. 3. 4. 5.]
5.0
----
2 7
4.0 [2. 3. 4. 5. 6.]
6.0
----
3 8
5.0 [3. 4. 5. 6. 7.]
7.0
----
4 9
6.0 [4. 5. 6. 7. 8.]
8.0
----
5 10
7.0 [5. 6. 7. 8. 9.]
9.0
----
6 11
8.0 [6. 7. 8. 9.]
9.0
----
+++++
1
+++++
0 4
-100.0 [   0. -100.    2.  100.]
100.0
----
0 5
2.0 [   0. -100.    2.  100.    4.]
100.0
----
1 6
100.0 [-100.    2.  100.    4.    5.]
100.0
----
2 7
4.0 [  2. 100.   4.   5.   6.]
100.0
----
3 8
5.0 [100.   4.   5.   6.   7.]
100.0
----
4 9
6.0 [4. 5. 6. 7. 8.]
8.0
----
5 10
7.0 [5. 6. 7. 8. 9.]
9.0
----
6 11
8.0 [6. 7. 8. 9.]
9.0
----


In [4]:
train_data

array([[   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
           9.],
       [   0., -100.,    2.,  100.,    4.,    5.,    6.,    7.,    8.,
           9.]])

In [5]:
train_data_pv

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
c = np.ndarray((3,3,2))
c[0] = [[1, 2], [3, 4], [5, 6]]
c[1] = [[7, 8], [9, 10], [11, 12]]
c[2] = [[13, 14], [15, 16], [17, 18]]
c[0, 1, 1]

4.0

In [7]:
c

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [44]:
from sklearn.preprocessing import MinMaxScaler

def preprocessing_train_data_Lstm(data, x_length, y_length):
    x_train = np.ndarray((data.shape[0], data.shape[1]-x_length-y_length, x_length, 1))
    y_train = np.ndarray((data.shape[0], data.shape[1]-x_length-y_length, y_length, 1))
    for window in range(0, data.shape[0]):
        scaler = MinMaxScaler(feature_range=(-1,1))
        scaled_data = scaler.fit_transform(data[window].reshape(-1,1))
        num = 0
        for x in range(x_length+y_length, len(scaled_data)):
            x_train[window, num] = scaled_data[x-x_length-y_length:x-y_length]
            y_train[window, num] = scaled_data[x-y_length:x]
            num+=1
    return x_train, y_train

In [45]:
scaler = MinMaxScaler(feature_range=(-1,1))

In [46]:
scaler.fit_transform(train_data[0].reshape(-1,1))

array([[-1.        ],
       [-0.77777778],
       [-0.55555556],
       [-0.33333333],
       [-0.11111111],
       [ 0.11111111],
       [ 0.33333333],
       [ 0.55555556],
       [ 0.77777778],
       [ 1.        ]])

In [47]:
train_data.shape

(2, 10)

In [48]:
x_length = 2
y_length = 2

In [49]:
train_data.shape[1]-x_length-y_length

6

In [50]:
x_train, y_train = preprocessing_train_data_Lstm(train_data, x_length, y_length)

In [51]:
x_train.shape

(2, 6, 2, 1)

In [52]:
import pandas as pd

def preprocessing_test_data_Lstm(train_data, test_data, x_length, y_length, slide):
    x_test = {}
    y_test = {}
    for i in test_data:
        scaler = MinMaxScaler(feature_range=(-1,1))
        model_inputs = pd.concat((train_data[i]['Close'].iloc[-x_length:], test_data[i]['Close'])).values
        model_inputs = model_inputs.reshape(-1,1)
        model_inputs = scaler.fit_transform(model_inputs)
        x_test[i] = []
        y_test[i] = []
        for x in range(x_length+y_length, len(model_inputs), slide):
            x_test[i].append(model_inputs[x-x_length-y_length:x-y_length])
            y_test[i].append(model_inputs[x-y_length:x])
        x_test[i], y_test[i] = np.array(x_test[i]), np.array(y_test[i])
        x_test[i] = np.reshape(x_test[i], (x_test[i].shape[0], x_test[i].shape[1], 1))
        y_test[i] = np.reshape(y_test[i], (y_test[i].shape[0], y_test[i].shape[1], 1))
    return x_test, y_test